config/routes.rb
Rails.application.routes.draw do
  root to: "statuses#index"
  resources :statuses, only: [:index, :new, :create] do
    resources :hands, only: [:new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deposit.rb
class Deposit < ActiveHash::Base
  self.data = [
    { id: 1, name: 0 },
    { id: 2, name: 1000 },
    { id: 3, name: 2000 },
    { id: 4, name: 3000 },
    { id: 5, name: 4000 },
    { id: 6, name: 5000 },
    { id: 7, name: 6000 },
    { id: 8, name: 7000 },
    { id: 9, name: 8000 },
    { id: 10, name: 9000 },
    { id: 11, name: 10000 }
  ]

  include ActiveHash::Associations
  has_many :statuses

end

app/models/hand.rb
class Hand < ApplicationRecord
  belongs_to :status
  
end

app/models/round_wind.rb
class RoundWind < ActiveHash::Base
  self.data = [
    { id: 1, name: '東' },
    { id: 2, name: '南' },
    { id: 3, name: '西' }
  ]

  include ActiveHash::Associations
  has_many :statuses

end

app/models/stacking_bar.rb
class StackingBar < ActiveHash::Base
  self.data = [
    { id: 1, name: 0 },
    { id: 2, name: 1 },
    { id: 3, name: 2 },
    { id: 4, name: 3 },
    { id: 5, name: 4 },
    { id: 6, name: 5 },
    { id: 7, name: 6 },
    { id: 8, name: 7 },
    { id: 9, name: 8 },
    { id: 10, name: 9 },
    { id: 11, name: 10 }
  ]

  include ActiveHash::Associations
  has_many :statuses
end

app/models/status.rb
class Status < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :deposit
  belongs_to :stacking_bar
  belongs_to :round_wind
  has_many :hands

  with_options presence: true do
    with_options format: { with: /\A[0-9]+\z/ },
                 numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100_000 } do
      validates :score_east
      validates :score_south     
      validates :score_west      
      validates :score_north     
    end
    validates :round_wind_id   
    validates :deposit_id      
    validates :stacking_bar_id 
    validates :seat_wind
  end 
  validate :sum_of_score_and_deposit
  
  def sum_of_score_and_deposit
    if score_east.present? and score_south.present? and score_west.present? and score_north.present? and deposit_id.present?
      error_message = "Please make sum of score and deposit 100,000 "
      errors.add(:base, error_message) unless (score_east + score_south + score_west + score_north + deposit_id == 100000)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hands_controller.rb
class HandsController < ApplicationController
  def new
    @hand = Hand.new
  end

  def create
    @status = Status.find(params[:status_id])
    @hand = @status.hands.new(hand_params)
    @hand.save
    @status = Status.find(params[:status_id])
    @hand = @status.hands.new(hand_params)
    render :new
  end

  def hand_params
    params.require(:hand).permit(
      :pai1,
      :pai2,
      :pai3,
      :pai4,
      :pai5,
      :pai6,
      :pai7,
      :pai8,
      :pai9,
      :pai10,
      :pai11,
      :pai12,
      :pai13,
      :pai14,
      :huro1_1, 
      :huro1_2, 
      :huro1_3, 
      :huro2_1, 
      :huro2_2, 
      :huro2_3, 
      :huro3_1, 
      :huro3_2, 
      :huro3_3, 
      :huro4_1, 
      :huro4_2, 
      :huro4_3, 
      :dora 
    )
    .merge(status_id: params[:status_id])
  end

  def show
  end
  
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  def index
  end

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      redirect_to new_status_hand_path(@status.id)
    else
      render :new
    end
  end

  private

  def status_params
    params.require(:status).permit(
      :score_east,    
      :score_south,   
      :score_west,    
      :score_north,   
      :seat_wind,  
      :round_wind_id, 
      :deposit_id,    
      :stacking_bar_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hands_helper.rb
module HandsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/hands/create.html.erb
<h1>fffffffff</h1>

app/views/hands/new.html.erb
<div class= "hand-input">
  <h1 class="hand-input-title">手牌入力画面<span class="notes">※13牌入力、テンパイの場合はアガリ牌が表示されます</span></h1>
  <div class="hand-choice">
    <div class="pai-list" >
      <%= image_tag "pai-images/man1-66-90-s-emb.png", alt:"一萬", name:1, id:"man1", class:"pais" %>
      <%= image_tag "pai-images/man2-66-90-s-emb.png", alt:"二萬", name:2, id:"man2", class:"pais" %>
      <%= image_tag "pai-images/man3-66-90-s-emb.png", alt:"三萬", name:3, id:"man3", class:"pais" %>
      <%= image_tag "pai-images/man4-66-90-s-emb.png", alt:"四萬", name:4, id:"man4", class:"pais" %>
      <%= image_tag "pai-images/man5-66-90-s-emb.png", alt:"五萬", name:5, id:"man5", class:"pais" %>
      <%= image_tag "pai-images/man6-66-90-s-emb.png", alt:"六萬", name:6, id:"man6", class:"pais" %>
      <%= image_tag "pai-images/man7-66-90-s-emb.png", alt:"七萬", name:7, id:"man7", class:"pais" %>
      <%= image_tag "pai-images/man8-66-90-s-emb.png", alt:"八萬", name:8, id:"man8", class:"pais" %>
      <%= image_tag "pai-images/man9-66-90-s-emb.png", alt:"九萬", name:9, id:"man9", class:"pais" %>
      <%= image_tag "pai-images/aka3-66-90-s-emb.png", alt:"赤五萬", name:5.1, id:"man0", class:"pais" %>
      <br>
      <%= image_tag "pai-images/pin1-66-90-s-emb.png", alt:"一筒", name:21, id:"pin1", class:"pais"%>
      <%= image_tag "pai-images/pin2-66-90-s-emb.png", alt:"二筒", name:22, id:"pin2", class:"pais"%>
      <%= image_tag "pai-images/pin3-66-90-s-emb.png", alt:"三筒", name:23, id:"pin3", class:"pais"%>
      <%= image_tag "pai-images/pin4-66-90-s-emb.png", alt:"四筒", name:24, id:"pin4", class:"pais"%>
      <%= image_tag "pai-images/pin5-66-90-s-emb.png", alt:"五筒", name:25, id:"pin5", class:"pais"%>
      <%= image_tag "pai-images/pin6-66-90-s-emb.png", alt:"六筒", name:26, id:"pin6", class:"pais"%>
      <%= image_tag "pai-images/pin7-66-90-s-emb.png", alt:"七筒", name:27, id:"pin7", class:"pais"%>
      <%= image_tag "pai-images/pin8-66-90-s-emb.png", alt:"八筒", name:28, id:"pin8", class:"pais"%>
      <%= image_tag "pai-images/pin9-66-90-s-emb.png", alt:"九筒", name:29, id:"pin9", class:"pais"%>
      <%= image_tag "pai-images/aka1-66-90-s-emb.png", alt:"赤五筒", name:25.1, id:"pin0", class:"pais"%>
      <br>
      <%= image_tag "pai-images/sou1-66-90-s-emb.png", alt:"一索", name:41, id:"sou1", class:"pais"%>
      <%= image_tag "pai-images/sou2-66-90-s-emb.png", alt:"二索", name:42, id:"sou2", class:"pais"%>
      <%= image_tag "pai-images/sou3-66-90-s-emb.png", alt:"三索", name:43, id:"sou3", class:"pais"%>
      <%= image_tag "pai-images/sou4-66-90-s-emb.png", alt:"四索", name:44, id:"sou4", class:"pais"%>
      <%= image_tag "pai-images/sou5-66-90-s-emb.png", alt:"五索", name:45, id:"sou5", class:"pais"%>
      <%= image_tag "pai-images/sou6-66-90-s-emb.png", alt:"六索", name:46, id:"sou6", class:"pais"%>
      <%= image_tag "pai-images/sou7-66-90-s-emb.png", alt:"七索", name:47, id:"sou7", class:"pais"%>
      <%= image_tag "pai-images/sou8-66-90-s-emb.png", alt:"八索", name:48, id:"sou8", class:"pais"%>
      <%= image_tag "pai-images/sou9-66-90-s-emb.png", alt:"九索", name:49, id:"sou9", class:"pais"%>
      <%= image_tag "pai-images/aka2-66-90-s-emb.png", alt:"赤五索", name:45.1, id:"sou0", class:"pais"%>
      <br>
      <%= image_tag "pai-images/ji1-66-90-s-emb.png", alt:"東", name:61, id:"ji1", class:"pais"%>
      <%= image_tag "pai-images/ji2-66-90-s-emb.png", alt:"南", name:62, id:"ji2", class:"pais"%>
      <%= image_tag "pai-images/ji3-66-90-s-emb.png", alt:"西", name:63, id:"ji3", class:"pais"%>
      <%= image_tag "pai-images/ji4-66-90-s-emb.png", alt:"北", name:64, id:"ji4", class:"pais"%>
      <%= image_tag "pai-images/ji6-66-90-s-emb.png", alt:"白", name:65, id:"ji5", class:"pais"%>
      <%= image_tag "pai-images/ji5-66-90-s-emb.png", alt:"發", name:66, id:"ji6", class:"pais"%>
      <%= image_tag "pai-images/ji7-66-90-s-emb.png", alt:"中", name:67, id:"ji7", class:"pais"%>
      <br>
    </div>
    <div class="btn-group">
      <label class="input-mode-btn" id="mode1-label" >手牌入力
        <input type="radio", name="input-mode" id="mode1" class="hidden" checked>
      </label>
      <label class="input-mode-btn" id="mode2-label" >ポン
        <input type="radio", name="input-mode" id="mode2" class="hidden">
      </label>
      <label class="input-mode-btn" id="mode3-label" >チー
        <input type="radio", name="input-mode" id="mode3" class="hidden">
      </label>
      <label class="input-mode-btn" id="mode4-label" >暗カン
        <input type="radio", name="input-mode" id="mode4" class="hidden">
      </label>
      <label class="input-mode-btn" id="mode5-label" >明カン
        <input type="radio", name="input-mode" id="mode5" class="hidden">
      </label>
      <label class="input-mode-btn" id="mode6-label">ドラ入力
        <input type="radio", name="input-mode" id="mode6"  class="hidden" >
      </label>
    </div>
  </div>
  <div class="hand-info">
    <div class="dora-wrap">
      ドラ:<%= image_tag "", size: "19x27", class:"dora", name:"dora", id:"dora", alt:"" %>
    </div>
    <div class="huro-info">
      <table class="huro-table1" id="huro-table1">
        <tr class="huro-table1-tr">
          <td class="huro-table1-td" id="huro-pai1-1"><%= image_tag "", id:"pai801", name:801, class:"huro-pai1" %></td>
          <td class="huro-table1-td" id="huro-pai1-2"><%= image_tag "", id:"pai802", name:802, class:"huro-pai1" %></td>
          <td class="huro-table1-td" id="huro-pai1-3"><%= image_tag "", id:"pai803", name:803, class:"huro-pai1" %></td>
        </tr>
      </table>
      <table class="huro-table2" id="huro-table2">
        <tr class="huro-table2-tr">
          <td class="huro-table2-td" id="huro-pai2-1"><%= image_tag "", id:"pai804", name:804, class:"huro-pai2" %></td>
          <td class="huro-table2-td" id="huro-pai2-2"><%= image_tag "", id:"pai805", name:805, class:"huro-pai2" %></td>
          <td class="huro-table2-td" id="huro-pai2-3"><%= image_tag "", id:"pai806", name:806, class:"huro-pai2" %></td>
        </tr>
      </table>
      <table class="huro-table3" id="huro-table3">
        <tr class="huro-table3-tr">
          <td class="huro-table3-td" id="huro-pai3-1"><%= image_tag "", id:"pai807", name:807, class:"huro-pai3" %></td>
          <td class="huro-table3-td" id="huro-pai3-2"><%= image_tag "", id:"pai808", name:808, class:"huro-pai3" %></td>
          <td class="huro-table3-td" id="huro-pai3-3"><%= image_tag "", id:"pai809", name:809, class:"huro-pai3" %></td>
        </tr>
      </table>
      <table class="huro-table4" id="huro-table4">
        <tr class="huro-table4-tr">
          <td class="huro-table4-td" id="huro-pai4-1"><%= image_tag "", id:"pai810", name:810, class:"huro-pai4" %></td>
          <td class="huro-table4-td" id="huro-pai4-2"><%= image_tag "", id:"pai811", name:811, class:"huro-pai4" %></td>
          <td class="huro-table4-td" id="huro-pai4-3"><%= image_tag "", id:"pai812", name:812, class:"huro-pai4" %></td>
        </tr>
      </table>
    </div>
    <table class="hand-table" id="hand-table">
      <tr class="hand-table-tr">
        <td class="hand-table-td" id="pai1"><%= image_tag "", id:"pai901", name:901, class:"pai" %></td>
        <td class="hand-table-td" id="pai2"><%= image_tag "", id:"pai902", name:902, class:"pai" %></td>
        <td class="hand-table-td" id="pai3"><%= image_tag "", id:"pai903", name:903, class:"pai" %></td>
        <td class="hand-table-td" id="pai4"><%= image_tag "", id:"pai904", name:904, class:"pai" %></td>
        <td class="hand-table-td" id="pai5"><%= image_tag "", id:"pai905", name:905, class:"pai" %></td>
        <td class="hand-table-td" id="pai6"><%= image_tag "", id:"pai906", name:906, class:"pai" %></td>
        <td class="hand-table-td" id="pai7"><%= image_tag "", id:"pai907", name:907, class:"pai" %></td>
        <td class="hand-table-td" id="pai8"><%= image_tag "", id:"pai908", name:908, class:"pai" %></td>
        <td class="hand-table-td" id="pai9"><%= image_tag "", id:"pai909", name:909, class:"pai" %></td>
        <td class="hand-table-td" id="pai10"><%= image_tag "", id:"pai910", name:910, class:"pai" %></td>
        <td class="hand-table-td" id="pai11"><%= image_tag "", id:"pai911", name:911, class:"pai" %></td>
        <td class="hand-table-td" id="pai12"><%= image_tag "", id:"pai912", name:912, class:"pai" %></td>
        <td class="hand-table-td" id="pai13"><%= image_tag "", id:"pai913", name:913, class:"pai" %></td>
        <td class="hand-table-td" id="pai14"><%= image_tag "", id:"pai914", name:914, class:"pai" %></td>
      </tr>
    </table>
  </div>
  <%= form_with model: [@status, @hand],url: status_hands_path ,id: "hand-form", local: true  do |f| %>
        <%= f.hidden_field :pai1 %>
        <%= f.hidden_field :pai2 %>
        <%= f.hidden_field :pai3 %>
        <%= f.hidden_field :pai4 %>
        <%= f.hidden_field :pai5 %>
        <%= f.hidden_field :pai6 %>
        <%= f.hidden_field :pai7 %>
        <%= f.hidden_field :pai8 %>
        <%= f.hidden_field :pai9 %>
        <%= f.hidden_field :pai10 %>
        <%= f.hidden_field :pai11 %>
        <%= f.hidden_field :pai12 %>
        <%= f.hidden_field :pai13 %>
        <%= f.hidden_field :pai14 %>
        <%= f.hidden_field :huro1_1 %>
        <%= f.hidden_field :huro1_2 %>
        <%= f.hidden_field :huro1_3 %>
        <%= f.hidden_field :huro2_1 %>
        <%= f.hidden_field :huro2_2 %>
        <%= f.hidden_field :huro2_3 %>
        <%= f.hidden_field :huro3_1 %>
        <%= f.hidden_field :huro3_2 %>
        <%= f.hidden_field :huro3_3 %>
        <%= f.hidden_field :huro4_1 %>
        <%= f.hidden_field :huro4_2 %>
        <%= f.hidden_field :huro4_3 %>
        <%= f.hidden_field :dora %>
      <div class="submit-btn-wrap">
        <%= link_to "打牌候補結果表示", "#", class: "submit-btn", id: "submit-btn-hand" %>
        <%= f.submit "手牌保存", class: "submit-btn", id: "submit-btn-hand-save" %>
      </div>
  <% end %>
</div>

<div class= "hand-output">
  <h1 class="hand-output-title">結果表示画面</h1>
  <div class="syanten-count-wrap" >
      シャンテン数： <span id="syanten-count-wrap"></span>
  </div>
  <div class="hand-output-table-title" >
      アガリ牌一覧
  </div>
  <table class="hand-output-table" id="hand-output-table">
    <tr class="hand-output-table-tr">
      <td class="hand-output-table-td" id="wish-pai1"><%= image_tag "", id:"pai701", name:701, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai2"><%= image_tag "", id:"pai702", name:702, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai3"><%= image_tag "", id:"pai703", name:703, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai4"><%= image_tag "", id:"pai704", name:704, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai5"><%= image_tag "", id:"pai705", name:705, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai6"><%= image_tag "", id:"pai706", name:706, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai7"><%= image_tag "", id:"pai707", name:707, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai8"><%= image_tag "", id:"pai708", name:708, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai9"><%= image_tag "", id:"pai709", name:709, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai10"><%= image_tag "", id:"pai710", name:710, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai11"><%= image_tag "", id:"pai711", name:711, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai12"><%= image_tag "", id:"pai712", name:712, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai13"><%= image_tag "", id:"pai713", name:713, class:"wish-pai" %></td>
      <td class="hand-output-table-td" id="wish-pai14"><%= image_tag "", id:"pai714", name:714, class:"wish-pai" %></td>
    </tr>
  </table>
</div>

app/views/hands/show.html.erb
wwwwwwww

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MahjongApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statuses/index.html.erb
<div class= "nav">
  <h1 class="app-name">麻雀交流・打牌選択補助ツール</h1>
  <div class= "dapai-assistance-botton">
    <%= link_to "打牌選択補助ツール", new_status_path, class: "to-dapai-assistance" %>
  </div>
  <div class= "chat-botton">
    <%= link_to "チャット画面(要ユーザー登録） ※近日公開予定", "#", class: "to-chat" %>
  </div>
</div>

app/views/statuses/new.html.erb
<%= form_with model: @status, url: statuses_path, id: "status-form", local: true do |f| %>
  <form>
    <div class= "status-input">
      <h1 class="status-input-title">状況入力画面</h1>
      <table class="detail-table">
        <thead>
          <tr>
            <td scope="col">場風</td>
            <td scope="col">本場</td>
            <td scope="col">供託</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="round-wind"><%= f.collection_select(:round_wind_id, RoundWind.all, :name, :name, {}, {}) %></td>
            <td class="stacking-bar"><%= f.collection_select(:stacking_bar_id, StackingBar.all, :name, :name, {}, {}) %></td>
            <td class="deposit"><%= f.collection_select(:deposit_id, Deposit.all, :name, :name, {}, {}) %></td>
          </tr>
        </tbody>
      </table>
      <table class="current-score-table">
        <thead>
          <tr>
            <th></th>
            <td scope="col">点数入力欄</td>
            <td scope="col">自風チェック欄</td>
          </tr>
        </thead>
        <tbody>
          <tr> 
            <th scope="row">東家</th>
            <td class="current-score"><%= f.text_field :score_east, placeholder: "例）25000", style: "border: none" %></td>
            <td class="seat-wind"><%= f.radio_button :seat_wind, "東" %></td>
          </tr>         
          <tr>
            <th scope="row">南家</th>
            <td class="current-score"><%= f.text_field :score_south, placeholder: "例）25000", style: "border: none" %></td>
            <td class="seat-wind"><%= f.radio_button :seat_wind, "南" %></td>
          </tr>
          <tr>
            <th scope="row">西家</th>
            <td class="current-score"><%= f.text_field :score_west, placeholder: "例）25000", style: "border: none" %></td>
            <td class="seat-wind"><%= f.radio_button :seat_wind, "西" %></td>
          </tr>
          <tr>
            <th scope="row">北家</th>
            <td class="current-score"><%= f.text_field :score_north, placeholder: "例）25000", style: "border: none" %></td>
            <td class="seat-wind"><%= f.radio_button :seat_wind, "北" %></td>
          </tr>
        </tbody>
      </table>
      <div class="submit-btn-wrap">
        <%= link_to "出力結果表示", "#", class: "submit-btn", id: "submit-btn-input" %>
      </div>
    </div>
    <div class= "status-output">
      <h1 class="status-output-title">状況出力画面</h1>
      <table class="output-table">
        <thead>
          <tr>
            <th></th>
            <td scope="col" rowspan="2">点差</td>
            <td scope="col" colspan="5">必要打点</td>
          </tr>
          <tr>
            <th></th>
            <td scope="col" >ツモ</td>
            <td scope="col" >ロン東</td>
            <td scope="col" >ロン南</td>
            <td scope="col" >ロン西</td>
            <td scope="col" >ロン北</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">東家</th>
            <td id="score-gap-east"></td>
            <td id="east-tsumo"></td>
            <td id="east-ron-from-east"></td>
            <td id="east-ron-from-south"></td>
            <td id="east-ron-from-west"></td>
            <td id="east-ron-from-north"></td>
          </tr>
          <tr>
            <th scope="row">南家</th>
            <td id="score-gap-south"></td>
            <td id="south-tsumo"></td>
            <td id="south-ron-from-east"></td>
            <td id="south-ron-from-south"></td>
            <td id="south-ron-from-west"></td>
            <td id="south-ron-from-north"></td>
          </tr>
          <tr>
            <th scope="row">西家</th>
            <td id="score-gap-west"></td>
            <td id="west-tsumo"></td>
            <td id="west-ron-from-east"></td>
            <td id="west-ron-from-south"></td>
            <td id="west-ron-from-west"></td>
            <td id="west-ron-from-north"></td>
          </tr>
          <tr>
            <th scope="row">北家</th>
            <td id="score-gap-north"></td>
            <td id="north-tsumo"></td>
            <td id="north-ron-from-east"></td>
            <td id="north-ron-from-south"></td>
            <td id="north-ron-from-west"></td>
            <td id="north-ron-from-north"></td>
          </tr>
        </tbody>
      </table>
      <div class="submit-btn-wrap">
        <%= f.submit "手牌入力へ", class:"submit-btn" %>
      </div>
    </div>
  </form>
<% end %>